server:
  port: 8888

spring:
  application:
    name: config-server

  security:
    user:
      name: ${CONFIG_SERVER_NAME}
      password: ${CONFIG_SERVER_PASSWORD}

  web:
    resources:
      add-mappings: false

  cloud:
    bus:
      enabled: true
    config:
      fail-fast: true
      monitor:
        enabled: true
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          timeout: 5
          searchPaths:
            - common
            - spring
            - fastapi
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include:
          - monitor

logging:
  file:
    name: /app/data/config-server.log
  level:
    root: INFO
