services:
  vault:
    image: vault:latest
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    volumes:
      - /var/vault:/vault/file
    networks:
      - nansan-network

networks:
  nansan-network:
    external: true