services:
  vault:
    image: vault:latest
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - /var/vault/file:/vault/file
      - /var/vault/logs:/vault/logs
    networks:
      - nansan-network

networks:
  nansan-network:
    external: true